{% set name = "openspecfun" %}
{% set version = "0.5.5" %}
{% set sha256 = "e3fcce3183005d5404ea5510cfb4c1d5639a42002336b36c6a7d2d8ed7811d2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JuliaLang/openspecfun/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-no-cc-override.patch
    - 0002-no-fc-override.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - openlibm 0.5.4

  run:
    - openlibm 0.5.4

test:
  commands:
    - test -f "${PREFIX}/include/Faddeeva.h"                             # [unix]
    - test -f "${PREFIX}/lib/libopenspecfun.a"                           # [unix]
    - test -f "${PREFIX}/lib/libopenspecfun${SHLIB_EXT}"                 # [unix]


about:
  home: https://github.com/JuliaLang/openspecfun
  license: MIT, Public Domain
  license_file: LICENSE.md
  summary: A collection of special mathematical functions
  dev_url: https://github.com/JuliaLang/openspecfun

extra:
  recipe-maintainers:
    - mkitti
    - dfornika
    - jakirkham
    - SylvainCorlay
